<?php

// database/migrations/2025_09_28_XXXXXX_create_urls_table.php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create the urls table.
     *
     * Notes:
     * - `user_id` is nullable so guests can shorten URLs (Phase 1),
     *   while authenticated users get ownership (Phase 2).
     * - `short_code` is always generated by us; `custom_alias` is optional
     *   and chosen by the user (Phase 5). The public code is custom_alias ?? short_code.
     * - `clicks_count` is a denormalized counter so the redirect path stays fast.
     */
    public function up(): void
    {
        Schema::create('urls', function (Blueprint $table) {
            $table->id();

            // Owner (nullable → guests allowed)
            $table->foreignId('user_id')
                ->nullable()
                ->constrained()
                ->cascadeOnDelete();

            // The original long URL
            $table->string('original_url', 2048);

            // System-generated short code (always unique)
            $table->string('short_code', 10)->unique();

            // Optional user-chosen alias (unique when present)
            $table->string('custom_alias', 50)->nullable()->unique();

            // Lifecycle flags (Phase 5)
            $table->timestamp('expires_at')->nullable();
            $table->boolean('is_active')->default(true);

            // Analytics denormalization (Phase 4)
            $table->unsignedBigInteger('clicks_count')->default(0);

            $table->timestamps();

            // Indexes for common lookups
            $table->index('user_id');
            $table->index('is_active');
            $table->index('expires_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('urls');
    }
};
